# Generated by Django 6.0.7 on 2026-07-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaia_variety",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
