# Generated by Django 6.0.7 on 2026-07-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0002_chaia_variety_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaia_variety",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
