# Generated by Django 6.0.7 on 2026-07-16 01:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0003_chaia_variety_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chai_Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comment", models.TextField(verbose_name="")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "chai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="first_app.chaia_variety",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first_app.chaia_variety",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "chai_varities",
                    models.ManyToManyField(
                        related_name="stores", to="first_app.chaia_variety"
                    ),
                ),
            ],
        ),
    ]
